"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# --- Variables de entorno (.env) leídas con django-environ ---
# Definimos tipos y valores por defecto para las variables que lo admiten.
env = environ.Env(
    DEBUG=(bool, False),
    ALLOWED_HOSTS=(list, ['127.0.0.1', 'localhost']),
)
# Carga el fichero .env de la raíz del proyecto (si existe).
environ.Env.read_env(BASE_DIR / '.env')

# La SECRET_KEY se lee del entorno: nunca se versiona en el código.
SECRET_KEY = env('SECRET_KEY')

# DEBUG y ALLOWED_HOSTS también provienen del .env.
DEBUG = env('DEBUG')
ALLOWED_HOSTS = env('ALLOWED_HOSTS')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # App propia
    'wrap',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Zona horaria local: relevante para calcular bien "el mes anterior" el día 1.
# Cámbiala si no estás en la España peninsular (p. ej. 'Atlantic/Canary').
TIME_ZONE = 'Europe/Madrid'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


# --- Logging rotativo ---
# El log de la app se escribe en logs/monthly_wrap.log con rotación automática.
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'detallado': {
            'format': '{asctime} [{levelname}] {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'consola': {
            'class': 'logging.StreamHandler',
            'formatter': 'detallado',
        },
        'fichero_rotativo': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'monthly_wrap.log',
            'maxBytes': 1024 * 1024,   # 1 MB por fichero
            'backupCount': 5,          # conserva 5 ficheros rotados
            'encoding': 'utf-8',
            'formatter': 'detallado',
        },
    },
    'loggers': {
        # Logger propio de la app (lo usarán los servicios y el command).
        'wrap': {
            'handlers': ['consola', 'fichero_rotativo'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}


# --- Spotify ---
# Credenciales y token leídos del .env. El refresh_token lo genera authorize_spotify.py.
SPOTIFY_CLIENT_ID = env('SPOTIFY_CLIENT_ID', default='')
SPOTIFY_CLIENT_SECRET = env('SPOTIFY_CLIENT_SECRET', default='')
SPOTIFY_REDIRECT_URI = env('SPOTIFY_REDIRECT_URI', default='http://127.0.0.1:8888/callback')
SPOTIFY_REFRESH_TOKEN = env('SPOTIFY_REFRESH_TOKEN', default='')
