# Generated by Django 6.0.5 on 2026-05-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateTimeField(auto_now_add=True, verbose_name='ejecutado el')),
                ('target_label', models.CharField(max_length=64, verbose_name='etiqueta del mes')),
                ('target_month', models.PositiveSmallIntegerField(verbose_name='mes objetivo')),
                ('target_year', models.PositiveIntegerField(verbose_name='año objetivo')),
                ('success', models.BooleanField(default=False, verbose_name='éxito')),
                ('playlist_id', models.CharField(blank=True, max_length=64, verbose_name='ID de playlist')),
                ('playlist_url', models.URLField(blank=True, verbose_name='URL de playlist')),
                ('track_count', models.PositiveSmallIntegerField(default=0, verbose_name='nº de canciones')),
                ('error_message', models.TextField(blank=True, verbose_name='mensaje de error')),
            ],
            options={
                'verbose_name': 'ejecución',
                'verbose_name_plural': 'ejecuciones',
                'ordering': ['-executed_at'],
            },
        ),
    ]
